### ISSUE TITLE
Create express server with 1 endpoint

### ISSUE THREAD

**Issue by jacobscarfmerrell** [jacobscarfmerrell/demeter#7]
Acceptance Criteria:
- a node/express endpoint needs to be created/exposed for the GET request
  - server can figure out date/time/zone stuff on its own

**Comment by jacobscarfmerrell** [comment]
@AlanLeePhilly this should have been done weeks ago

**Comment by jacobscarfmerrell** [comment]
my joke from the day we made this ticket now seems very aggressive... sry not sry. I put a JSON file in the API repo with the zones, which should be helpful when we get to seeding the db

**Comment by AlanLeePhilly** [comment]
Hah! Was just looking at this last night. Right now because I'm so hot for
my new windows laptop I'm trying to force myself to do all of my side proj
work on this machine, so it's been a lot of navigating installing
bash/node/npm/etc. Woohooo for breaking down platform boundaries, but what
a pain to learn surgery on a new animal.

**Comment by jacobscarfmerrell** [comment]
are you using WSL? it helps a bit

**Comment by AlanLeePhilly** [comment]
iyam!

**Comment by AlanLeePhilly** [comment]
done't https://github.com/jacobscarfmerrell/demeter-api/commit/9fc7300d2ade211192db9ce4545e047e7958152f
